import os from 'os'
import path from 'path'

const chunkMs = 30000
const recFallbackDir = path.join(os.homedir(), "Documents", "Terac", "Recordings")
const roomUrl = 'wss://terac-test-luzsolx8.livekit.cloud'
const rendererRoomToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzYzOTM4MzEsImlkZW50aXR5IjoicmVuZGVyZXIiLCJpc3MiOiJBUElvUkc2OUFHRHlhTWciLCJuYW1lIjoicmVuZGVyZXIiLCJuYmYiOjE3NzM4MDE4MzEsInN1YiI6InJlbmRlcmVyIiwidmlkZW8iOnsicm9vbSI6InRlc3Rfcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.52cL-pxEFxXiFvoxHA4AyL9oqlvtnbNDkCmOg-JoPXY'
const mainRoomToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzYzOTM4MzEsImlkZW50aXR5IjoibWFpbiIsImlzcyI6IkFQSW9SRzY5QUdEeWFNZyIsIm5hbWUiOiJtYWluIiwibmJmIjoxNzczODAxODMxLCJzdWIiOiJtYWluIiwidmlkZW8iOnsicm9vbSI6InRlc3Rfcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.TWWUtFgoDMzw4ST4Kz9m75oDlxkrJSP2jDHB8I0CXLs'

export { recFallbackDir, roomUrl, mainRoomToken, rendererRoomToken, chunkMs }