import os from 'os'
import path from 'path'

const chunkMs = 30000
const recFallbackDir = path.join(os.homedir(), "Documents", "Terac", "Recordings")
const roomUrl = 'wss://terac-test-luzsolx8.livekit.cloud'
const rendererRoomToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzM4MDA5NzcsImlkZW50aXR5IjoicmVuZGVyZXIiLCJpc3MiOiJBUElvUkc2OUFHRHlhTWciLCJuYW1lIjoicmVuZGVyZXIiLCJuYmYiOjE3NzM3MTQ1NzcsInN1YiI6InJlbmRlcmVyIiwidmlkZW8iOnsicm9vbSI6InRlc3Rfcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.prYnw3E5PHZdwjOoetZsK0cSpNgtCUA9-LtyilSDGXU'
const mainRoomToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzM4MDA5NzcsImlkZW50aXR5IjoibWFpbiIsImlzcyI6IkFQSW9SRzY5QUdEeWFNZyIsIm5hbWUiOiJtYWluIiwibmJmIjoxNzczNzE0NTc3LCJzdWIiOiJtYWluIiwidmlkZW8iOnsicm9vbSI6InRlc3Rfcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.1kEV31YgKsnCteyaNlQLmxipEsywDpnv80VhJivkEy8'

export { recFallbackDir, roomUrl, mainRoomToken, rendererRoomToken, chunkMs }